### ISSUE TITLE
Staking Rewards and Wallet Balance not Working

### ISSUE THREAD

**Issue by enes-oerdek** [enes-oerdek/Home-Assistant-Helium-Integration#15]
Hello Folks, it was a little calm recently, due to my recent change in employment. Soon I will be able to provide more updates and provide enhancements.

Since today morning, staking rewards are not calculated any more. This issue is known and will be tackled as soon as possible. Subscribe to this issue to be notified about updates.

**Comment by datascope11** [comment]
Hi Enes, thanks for taking a look. Appears for me that all entities provided by this integration (wallet balances, prices etc...) stopped working and reporting a couple of days ago, Nov 5th.

**Comment by enes-oerdek** [comment]
This issue has been resolved. Sorry for the trouble.

The existing issues were due to the solana endpoint this app is using. Due do its free nature, availability is sometimes an issue. In upcoming releases changing to a paid endpoint might be something to consider.

For now I will close this issue.
