### ISSUE TITLE
solana wallet function: not working?

### ISSUE THREAD

**Issue by askmurphy** [enes-oerdek/Home-Assistant-Helium-Integration#18]
After updating my HA with this integration, my (added) Solana wallet is not visible in this integration?
Rebooting HA server, same issue...

Checked the Solana wallet in my Helium wallet: still available and alive ?

**Comment by nict41** [comment]
Same here

**Comment by DApps-Representative** [comment]
> After updating my HA with this integration, my (added) Solana wallet is not visible in this integration? Rebooting HA server, same issue...
> 
> Checked the Solana wallet in my Helium wallet: still available and alive ?




 Hey there @askmurphy!

Thank you for reaching out! hi, it seems your address was blacklisted: kindly refresh your wallet, if the issue persists, then your query would be best dealt with by the support team.
 I’ll have to refer you to the official support Team with the ticket ID HEL7463
 
Please see the link below to our dedicated support line: 
 [Helium Wallet Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.

**Comment by askmurphy** [comment]
Yeah, right....

**Comment by maco2035** [comment]
Yeah mine is dead too, It might be the api is down? Who knows, but it isn't working.

**Comment by askmurphy** [comment]
> > After updating my HA with this integration, my (added) Solana wallet is not visible in this integration? Rebooting HA server, same issue...
> 
> > 
> 
> > Checked the Solana wallet in my Helium wallet: still available and alive ?
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  Hey there @askmurphy!
> 
> 
> 
> Thank you for reaching out! hi, it seems your address was blacklisted: kindly refresh your wallet, if the issue persists, then your query would be best dealt with by the support team.
> 
> 
> I’ll have to refer you to the official support Team with the ticket ID HEL7463
> 
> 
> 
> 
> Please see the link below to our dedicated support line:
> 
> 
> 
> [Helium Wallet Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
> 
> 
> 
> 
> 
> 
> Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.
> 
> 
> 

Reported this dappwallet guy: phishing!!!

**Comment by enes-oerdek** [comment]
I am sorry about the issues. The issue occurred on the backend during my absence. Issue has been resolved and should now work without further issues.

The number of users of this integration increased a lot. But we are using free a free solana endpoint, which run into rate limits with this many users. For now I will continue to use the free endpoint and switch to a paid one soon. If someone can "donate" a paid endpoint, please let me know :)

**Comment by maco2035** [comment]
@enes-oerdek Is it possible for you to open source the back-end or put it as an hacs/adon to HA? It would be nice to run it locally!
