### ISSUE TITLE
Not all miners showing up

### ISSUE THREAD

**Issue by mattfox27** [enes-oerdek/Home-Assistant-Helium-Integration#2]
Hi..Awesome Project BTW, thank you so much...I just set this up and its not showing all of my miners its showing like 3 of 4

**Comment by enes-oerdek** [comment]
> Hi..Awesome Project BTW, thank you so much...I just set this up and its not showing all of my miners its showing like 3 of 4

@mattfox27 Thank you for trying out and reporting this issue! Feedback is highly appreciated :)

This plugin uses a backend to calculate the hotspot rewards, which is quite complex. I think I might have found the issue for this effect. Could you please check, whether you now see all of your hotspots?

**Comment by mattfox27** [comment]
Yes it looks like now I can see all of them, it would be awesome to be able to see daily rewards for each miner if possible

**Comment by enes-oerdek** [comment]
> Yes it looks like now I can see all of them, it would be awesome to be able to see daily rewards for each miner if possible

This is exactly what this integration does. You should see all of your rewards, as soon as the data is on the blockchain, with minor latencies.
Your issue here occurred because of synchronizing issues with the blockchain. The programming already updates latest data from the blockchain, but since the rewards are only added on-chain once a day, you will find only one update per day for rewards. The off-chain data with witnesses, beacons and data transfer will also be added at some point. But I do not know when exactly. 

Currently I work on getting staking rewards into this integration. This will probably take some more weeks, and then I will see what to consider next from the roadmap :)

I hope you will like upcoming updates! Feel free to raise issues anytime you have feedback or any issue.

**Comment by mattfox27** [comment]
Yes it does show total rewards which is awesome, what I would love to see is rewards per miner in a 24hr period that would be awesome...loving the plugin though exactly what I was looking for.  I had it all setup before Solana migration than it stopped working after, so thankful

**Comment by enes-oerdek** [comment]
> Yes it does show total rewards which is awesome, what I would love to see is rewards per miner in a 24hr period that would be awesome...loving the plugin though exactly what I was looking for. I had it all setup before Solana migration than it stopped working after, so thankful

Actually that is already possible, I just had no time to update the examples. Simply do the following.

1. Open your Devices and Sensors, and switch to "Helpers"-Tab.
![Screenshot from 2023-05-28 22-06-08](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/5871793/c571fc6b-c3a1-41b3-9e56-7fbe8eefd676)

2. Create a new Helper and select "Utility Meter". Configure like follows (e.g. with your "Wallet Total Rewards")
![Screenshot from 2023-05-28 22-12-23](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/5871793/4a576c0b-052b-4fa6-b709-4b3a31b5e6c9)

Now you can simply use this newly created sensor for tracking your daily rewards. Here is an example with a "mini-graph-card" graph (mine was set up just recently, so I only have data for two days):
![grafik](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/5871793/a165ad13-2551-404e-baa7-5072b038db75)

`entities:
  - entity: sensor.daily_hotspot_reward_wallet_3adg
hours_to_show: 480
name: Daily Rewards for Wallet
group_by: date
aggregate_func: max
show:
  graph: bar
  icon: false
  state: true
type: custom:mini-graph-card
`

At some point I will provide add better examples. But for now this should help you.

**Comment by mattfox27** [comment]
Awesome, thanks for the guide....I got it working...your the best!!!

**Comment by mattfox27** [comment]
Also some of my sensors do not show IOT at the end of the number value, the first sensor does but not the others, I can send a photo to show you...

**Comment by enes-oerdek** [comment]
> Also some of my sensors do not show IOT at the end of the number value, the first sensor does but not the others,
> 
> ![20230529_192955.jpg](https://user-images.githubusercontent.com/6801877/241833159-48e0304f-a337-43a1-a5aa-97ff16ed033a.jpg)

My guess is, that three of your sensors still have only one dataset. After some days, it might be fixed automatically, like you have it for "Iguana". The unit of measurement is automatically derived from the underlying sensor, which should be IOT in these cases. Let's wait and see. Let me know after some days, if the measure is still not visible.

Restarting your home assistant might also help.

**Comment by enes-oerdek** [comment]
@mattfox27 Could you let me know, whether it works now, or still the same issue?

**Comment by mattfox27** [comment]
Looks like still same ![Screenshot_20230531_143900_Home Assistant.jpg](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/6801877/974ee0b5-42f0-4d8c-832c-5e7166a4004b)

![Screenshot_20230531_143906_Home Assistant.jpg](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/6801877/ea059246-f6a0-467d-83b2-5d4e80623dab)

**Comment by CumpsD** [comment]
How often do the Claimed and Unclaimed sensor of a hotspot update? I noticed wallet and stakes are instantly, but my hotspots stay with unclaimed rewards, even after I claimed them all.

**Comment by enes-oerdek** [comment]
> How often do the Claimed and Unclaimed sensor of a hotspot update? I noticed wallet and stakes are instantly, but my hotspots stay with unclaimed rewards, even after I claimed them all.

(Un)claimed rewards should update within one or two hours. There is a very simple cache applied so that the backend does not face too much load. I did a test with my own wallet. It seems there is indeed an error with that cache. It did not update and should be fixed now. Please let me know, if you face an issue again.

**Comment by CumpsD** [comment]
> (Un)claimed rewards should update within one or two hours. There is a very simple cache applied so that the backend does not face too much load. I did a test with my own wallet. It seems there is indeed an error with that cache. It did not update and should be fixed now. Please let me know, if you face an issue again.

There doesn't seem to be a commit/release yet :)
