### ISSUE TITLE
Unclaimed Rewards Remain Unclaimed after Claiming

### ISSUE THREAD

**Issue by datascope11** [enes-oerdek/Home-Assistant-Helium-Integration#3]
Loving this custom component, great work! 
Claimed all rewards over a week ago, and figured this was a timing thing. However the Unclaimed Reward sensor continues to grow daily and continues to include the rewards claimed over a week ago, no longer matching my wallet and miner numbers. 

Example: 

**Miner & Wallet Integration:**

![image](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/67964685/fad8c7e5-9d79-4619-b8c4-33b15a125dd3)

**Wallet App Unclaimed:**

![IMG_0970](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/67964685/22b3a228-5c37-4910-a4a5-b98acbfd2727)

**Wallet App Balance (Claimed)**

![IMG_0969](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/67964685/ece4402d-1099-4970-b09f-266cdfa373db)

(The difference in the total integration of 41,923 and the sum of the Wallet App of ~47k is the airdrop of IoT at the launch of the Solana chain).

**Comment by CumpsD** [comment]
Same issue here. I have claimed all rewards, but in HA it is still listed as unclaimed.

**Comment by Anashost** [comment]
Same and HA logs has errors related to this integration.

**Comment by enes-oerdek** [comment]
Thanks a lot everyone for filing this issue. Could you please check it out again, and give me a short info, whether it works now? 

This plugin depends on a little backend service, which collects the required data. To not get too much load, I introduced caching, but there was an error with the cache. It only occasionally updated and caused this issue. 

Please test it out and let me know, if the data updates. It should update latest within half an hour. Sensors anyway update only every 10 minutes by default. The caching of onchain data on backend side has 20 minutes cache. So in total max delay should be 30 minutes.

**Comment by enes-oerdek** [comment]
> Loving this custom component, great work!

I am glad you like it! Feel free to raise further issues, in case you have problems :) I am happy to work on getting this plugin to a more mature state.

**Comment by CumpsD** [comment]
Is it possible to share the code from `http://solana.oerdek.com` so we can run this backend service ourself too? It will take away load from your servers + from a privacy point of view it might raise less eyebrows?

**Comment by enes-oerdek** [comment]
> Is it possible to share the code from `http://solana.oerdek.com` so we can run this backend service ourself too? It will take away load from your servers + from a privacy point of view it might raise less eyebrows?

I prepared the github project for the backend and consider sharing that as well :)

**Comment by CumpsD** [comment]
> I prepared the github project for the backend and consider sharing that as well :)

Thanks! Looking forward for that :) I'll run it on my k8s cluster at home then ;)

**Comment by datascope11** [comment]
Unclaimed rewards updated around 2:30pm EST for me, and seems to be accurate now. I will check in again tomorrow. Thanks!

**Comment by CumpsD** [comment]
> > Is it possible to share the code from `http://solana.oerdek.com` so we can run this backend service ourself too? It will take away load from your servers + from a privacy point of view it might raise less eyebrows?
> 
> I prepared the github project for the backend and consider sharing that as well :)

Any chance you had time to place this online so we can run it locally? :)
