### ISSUE TITLE
Statistics shown as Unavailable

### ISSUE THREAD

**Issue by CumpsD** [enes-oerdek/Home-Assistant-Helium-Integration#4]
This has worked before, but suddenly all general stats fell to `Unavailable`:

![image](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/1201644/63442442-a1d4-4518-8f8e-fdef7091808b)

**Comment by enes-oerdek** [comment]
Please try to reload the plugin or restart your home assistant, and please tell me whether this worked.

If this did not help, could you please provide me the contents of your home assistant log? You can find that log in your home assistant root folder, with filename 'home-assistant.log'. Probably you have something personal there. You can also send it to me via mail to genesis@proxer.de or via discord to @milchtuetenente.

**Comment by soonic6** [comment]
today run into the same problem. restating HA and/or reload the plugin didn't work.
@enes-oerdek  i will send you my logs via discord.

**Comment by ragman11** [comment]
Have the same Problem since yesterday night. all sensors unavailable.

**Comment by enes-oerdek** [comment]
@soonic6 @ragman11 @CumpsD 
Thanks a lot for raising the issue. With the latest release, this bug has been fixed.
