### ISSUE TITLE
Error while setting up helium_solana platform for sensor

### ISSUE THREAD

**Issue by ZL1LAC** [enes-oerdek/Home-Assistant-Helium-Integration#6]
Logger: homeassistant.components.sensor
Source: custom_components/helium_solana/api/backend.py:17
Integration: Sensor
First occurred: 7:13:30 PM (1 occurrences)
Last logged: 7:13:30 PM
Error while setting up helium_solana platform for sensor

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/helium_solana/sensor.py", line 77, in async_setup_entry
    sensors = await get_sensors(wallets, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helium_solana/sensor.py", line 145, in get_sensors
    response = await api_backend.get_data('staking-rewards/'+str(wallet))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helium_solana/api/backend.py", line 28, in get_data
    response = await asyncio.to_thread(self.http_client, path, None, 'GET', headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helium_solana/api/backend.py", line 17, in http_client
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://solana.oerdek.com/staking-rewards/xxxx
```

**Comment by enes-oerdek** [comment]
Thank you @ZL1LAC for raising an issue. Until last week, I was not able to provide support due to my full-time occupation. I hope I can now support you in resolving this issue.

For me this seems like a temporary issue with the backend. I would like to ask you to try again, in case you still struggle with the issue. I will check out the logs and resolve the issue.

**Comment by enes-oerdek** [comment]
@ZL1LAC could you please provide me an update? Do you still face issues with this integration, or is it resolved? 
If you still face issues, can you please provide me your solana wallet address, so that I can debug this? You can either provide it via comment, or via discord: @milchtuetenente

**Comment by ZL1LAC** [comment]
Yeah still having issues.

Here is my wallet address to debug.

`ETQSVsKZfHDpE77cZdz3mpCJSm8Qn13SKN1ryJt7gXnt`

**Comment by enes-oerdek** [comment]
On the latest stable version of Home Assistant, your wallet can be added without any issues on my instance:
![grafik](https://github.com/enes-oerdek/Home-Assistant-Helium-Integration/assets/5871793/60810524-e84a-4a99-ab96-86527fd5b247)

Could you please provide me your home assistant logs and the version of home assistant you are using? Your HA version you can get in Settings > About. Also please provide me the log, which shows the error. I want to check, whether the error message changed or whether it is the same.

**Comment by ZL1LAC** [comment]
Hang on!  I'M SUCH A KNOB!!!!!  I had the wrong Integration installed!  Let me get my sh*# together and report back.

**Comment by ZL1LAC** [comment]
I can confirm it was the wrong hass add-on i had installed.  Sorry for not checking before posting an issue.

**Comment by enes-oerdek** [comment]
Thanks for checking! Great that it works now. Have fun with the integration! In case you have further feedback, issues or ideas, be welcome to create another issue :)
