### ISSUE TITLE
Detection of new miner 

### ISSUE THREAD

**Issue by bttfw** [enes-oerdek/Home-Assistant-Helium-Integration#7]
How long does it take to recognize new devices I installed a new miner 4 days ago it has earnings but neither the unclaimed rewards or the miner is showing up 

Is their a way to manually update the integration?

Also what about offline devices they don't show up I guess because they don't earn anything but they should still belong to the wallet 

Anyhow thanks for the amazing integration I bet this will be really good over time

**Comment by enes-oerdek** [comment]
Thank a lot for raising the issue. I haven't been able to test new miners. I will try to find out some new miners, which are available on the blockchain and check out what is causing this issue. I will let you know as soon as I have some results.

In case it just takes some time, I will investigate why it takes this time. Actually it should use (almost) live blockchain data.

**Comment by bttfw** [comment]
> Thank a lot for raising the issue. I haven't been able to test new miners. I will try to find out some new miners, which are available on the blockchain and check out what is causing this issue. I will let you know as soon as I have some results.
> 
> In case it just takes some time, I will investigate why it takes this time. Actually it should use (almost) live blockchain data.

Thanks 

It's still not showing up so the issue is still their 

Thanks again it's a great and helpful integration

**Comment by enes-oerdek** [comment]
Thanks a lot for your response @bttfw . Until last week I was heavily occupied with my full-time occupation and could not follow up. In the upcoming weeks I will try to support you in getting this run.

For now, I would like to ask you to send me your solana wallet id. I want to check out, what data we get from the backend and debug this issue. In case you want to leave your wallet id private, I would like to ask you to send me your id via discord on "milchtuetenente".

Hope to hear back from you.

**Comment by bttfw** [comment]
B1sN9Bg5tjvQcXWLbNvy3oxARXxFFqj8HFjnh5jHcpd8

Thanks

**Comment by enes-oerdek** [comment]
Thanks a lot @bttfw . Could you please also tell me the name of the hotspot you are missing?

**Comment by bttfw** [comment]
Dazzling Arctic Perch

For example it's a couple more but they are offline 

If you plan to do updates in the future something nice would be a simple list of your devices with online offline status

**Comment by enes-oerdek** [comment]
Additional Info: Got the issue. Hotspots having no rewards were not considered in the calculation of rewards. I will add this in the upcoming days. Will need some more days, to test the changes before deploying. I will let you know, when this is fixed.

**Comment by enes-oerdek** [comment]
@bttfw I just fixed this issue and deployed the backend again. You should be able to see all of your hotspots in the devices, after you restart your home assistant or add the integration again. Could you please check and let me know if everything works out as expected?

**Comment by bttfw** [comment]
Yes all devices show up thank you 

But everything else stopped working 😅

Can't see the earnings etc
